version: '3.8'
services:
  sgd-bridge-app:
    build: .
    container_name: sgd-bridge-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - tmt-sgd

  sgd-bridge-nginx:
    image: nginx:alpine
    container_name: sgd-bridge-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sgd-bridge-app
    networks:
      - tmt-sgd

networks:
  tmt-sgd:
    external: true
