version: '3.8'
services:
  app:
    build: .
    container_name: sgd-bridge
    ports:
      - "8081:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
    command: php artisan serve --host=0.0.0.0 --port=8000
